apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
    name: cluster-logging-operator
    namespace: openshift-marketplace
    annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        ran.openshift.io/deprecation-warning: "source-cr ClusterLogCatSource.yaml is deprecated, please use DefaultCatSource.yaml instead"
spec:
    displayName: Openshift Cluster Logging Operator
    icon:
        base64data: ""
        mediatype: ""
    image: {{ .spec.image }}
    publisher: Red Hat
    sourceType: grpc
